### ISSUE TITLE
Different behavior with fuzzywuzzy

### ISSUE THREAD

**Issue by sillybun** [rapidfuzz/RapidFuzz#102]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/15951598/116810916-fb91e580-ab78-11eb-8573-89552aed63b5.png">

```
In [25]: import fuzzywuzzy                                                     

In [26]: import rapidfuzz                                                      

In [27]: rapidfuzz.fuzz.ratio("prod", "random")                                
Out[27]: 40.0

In [28]: fuzzywuzzy.fuzz.ratio("prod", "random")                               
Out[28]: 40

In [29]: rapidfuzz.fuzz.partial_ratio("prod", "random")                        
Out[29]: 50.0

In [30]: fuzzywuzzy.fuzz.partial_ratio("prod", "random")                       
Out[30]: 25
```

**Comment by sillybun** [comment]
I don't know whether it's a bug or it's a feature. But the difference of `partial_ratio` makes me confused.

**Comment by sillybun** [comment]
I think it's a bug of fuzzywuzzy? because in fuzzywuzzy, "pred" is more similar to "random" than "prod". I cannot understand why.

**Comment by sillybun** [comment]
https://github.com/seatgeek/fuzzywuzzy/issues/313

**Comment by maxbachmann** [comment]
This is a bug in FuzzyWuzzy. You can find my explanation in your issue at FuzzyWuzzy: https://github.com/seatgeek/fuzzywuzzy/issues/313

**Comment by sillybun** [comment]
Thanks a lot!!! great work~
