### ISSUE TITLE
process.extractOne matching non word character strings as completely accurate (100.0)

### ISSUE THREAD

**Issue by m1stermanager** [rapidfuzz/RapidFuzz#110]
```python
from rapidfuzz import process

process.extractOne("+", ["-"])
```
results in `('-', 100.0, 0)`

if I set processor=None I get `('-', 0.0, 0)`, but it messes up my other matches

background:
we were attempting to port over to this from fuzzywuzzy and were hoping for minimal differences. if this is expected, it would be awesome to know the best way to get the desired result.....

It looks like after the default preprocessing both values are "", which obviously matches exactly.... empty strings appear to not match in fuzzywuzzy... would be great to have a workaround! thanks!

**Comment by maxbachmann** [comment]
Hm FuzzyWuzzy is a bit inconsistent on this:
```
>>> from fuzzywuzzy import fuzz
>>> fuzz.ratio("","")
100
>>> fuzz.partial_ratio("","")
100
>>> fuzz.token_sort_ratio("","")
100
>>> fuzz.partial_token_sort_ratio("","")
100

>>> fuzz.token_set_ratio("","")
0
>>> fuzz.partial_token_set_ratio("","")
0
fuzz.WRatio("","")
0
>>> fuzz.QRatio("","")
0
```

In RapidFuzz empty strings are always treated as perfect matches so far:
```
>>> from rapidfuzz import fuzz
>>> fuzz.ratio("","")
100
>>> fuzz.partial_ratio("","")
100
>>> fuzz.token_sort_ratio("","")
100
>>> fuzz.partial_token_sort_ratio("","")
100

>>> fuzz.token_set_ratio("","")
100
>>> fuzz.partial_token_set_ratio("","")
100
fuzz.WRatio("","")
100
>>> fuzz.QRatio("","")
100
```

Since I want `rapidfuzz.fuzz` to be a direct replacement of `fuzzywuzzy.fuzz` I consider this as a bug. I will fix this in the next Release.

**Comment by m1stermanager** [comment]
thanks for the quick response. obviously on our end a little preprocessing could avoid the whole issue, but would be awesome to get that consistency. 

thanks so much!

**Comment by maxbachmann** [comment]
This is fixed in main now (https://github.com/maxbachmann/RapidFuzz/commit/370190b088b049263f57365cac28c9eba1bb788e) and will be part of the next release.
