### ISSUE TITLE
Different results for extractOne on dataset size change

### ISSUE THREAD

**Issue by wasi-master** [rapidfuzz/RapidFuzz#145]
So I was testing this out and this happened
```python
>>> rapidfuzz.process.extractOne("rthd", ["readthedocs", "regex-search"], scorer=rapidfuzz.fuzz.WRatio)
('readthedocs', 67.5, 0)
>>> rapidfuzz.process.extractOne(
... "rthd", 
... ['browse', 'cache-clear', 'cache-info', 'cache-refresh', 'description', 'information',
...  'largest-files', 'new-packages', 'new-releases', 'read-the-docs', 'regex-search',
...   'releases', 'search'],
... scorer=rapidfuzz.fuzz.WRatio
)
('regex-search', 51.42857142857143, 10)
```

Matching with `rthd`, 
When only 2 items are given (`readthedocs` and `regex-search`), it returns the correct one which is `readthedocs` with the score 67.5
When there are more items given (13), it returns `regex-search` now with the score 51.42. Why isn't `readthedocs` being shown here? am I doing something wrong? was this the intended outcome? 

I'm sorry if this has been asked before

**Comment by maxbachmann** [comment]
The second list includes `read-the-docs`  instead of `readthedocs`. This changed string has a lower similarity to `rthd`:
```python
>>> rapidfuzz.fuzz.WRatio("rthd", "read-the-docs")
48.857142857142854
```
so it is no longer the best match.

**Comment by wasi-master** [comment]
Oh, thanks I'll make sure to remove hyphens

**Comment by wasi-master** [comment]
Is there any way for rapidfuzz to ignore hyphens tho. Because if I remove hyphens manually and pass it as choices then I'll get the result without the hyphens but I need it with hyphens

**Comment by wasi-master** [comment]
Nevermind I just did something about that (made an mapping of non-hyphenated to hyphenated)

**Comment by maxbachmann** [comment]
You can pass a custom preprocessor function to process.extractOne:
```python
rapidfuzz.process.extractOne("rthd", ["readthedocs", "regex-search"],
    processor=my_preprocessor, scorer=rapidfuzz.fuzz.WRatio
)
```

**Comment by wasi-master** [comment]
Oh thanks. Great library btw
