### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by maxbachmann** [rapidfuzz/RapidFuzz#17]
the current documentation is mainly copy pasted from FuzzyWuzzy since the functions can be used in the same way. However many features are not properly documented and therefore lead to people using FuzzyWuzzy in an unoptimal way.

**Comment by TrigonaMinima** [comment]
I'd like to help setup the documentation. Do you think we can go ahead with [read the docs](https://docs.readthedocs.io/en/stable/index.html)?

**Comment by maxbachmann** [comment]
yes readthedocs would be my choice aswell. Help is always appreciated :)

**Comment by maxbachmann** [comment]
A first version of the docs is now available here: https://maxbachmann.github.io/RapidFuzz/

**Comment by TrigonaMinima** [comment]
The #35 pull should help with the function documentation wrt to parameters and return values, but we still need to document the behavior/process of composite ratio methods (eg: WRatio). Process/behavior like here: https://github.com/maxbachmann/rapidfuzz/issues/29#issuecomment-622562966

**Comment by Tetsujinfr** [comment]
Fyi https://maxbachmann.github.io/rapidfuzz/ return 404. Is there a new place for the documentation? (beyond the readme.md)

Edit: Ok my bad, I went to fast on the readme, and I did not see the new documentation [address](https://maxbachmann.github.io/RapidFuzz/fuzz.html) 
All good thanks
