### ISSUE TITLE
fuzz.partial_ratio - get some indicator to differentiate between an exact match and a partial match

### ISSUE THREAD

**Issue by NikhilKothari** [rapidfuzz/RapidFuzz#171]
```
Query = "boy"

Sentence1 = "boycott them"
Sentence2 = "It's a boy"
```
```
fuzz.partial_ratio(Query, Sentence1)
>> 100.0

fuzz.partial_ratio(Query, Sentence2)
>> 100.0
```

@maxbachmann Is it possible to know an exact match (Sentence2) different from a partial match (Sentence1) while using fuzz.partial_ratio?

**Comment by maxbachmann** [comment]
`fuzz.partial_ratio` does not allow differentiating an exact match of a word from a partial match. It is however possible to split the sentences into words before matching:
```python
>>> fuzz.partial_ratio(Query.split(), Sentence1.split())
0.0
>>> fuzz.partial_ratio(Query.split(), Sentence2.split())
100.0
```
