### ISSUE TITLE
pybind11 with iterables

### ISSUE THREAD

**Issue by maxbachmann** [rapidfuzz/RapidFuzz#2]
right now only lists are accepted, but it should be possible to convert any iterable to a vector

**Comment by maxbachmann** [comment]
implemented conversions to from any iterables to list

**Comment by nonos12345** [comment]
> right now only lists are accepted, but it should be possible to convert any iterable to a vector

**Comment by maxbachmann** [comment]
Not sure what you mean. Is something not working for you? I don't even use pybind11 anymore. So if there is a problem this should probably be a separate issue.
