### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by zhems** [rapidfuzz/RapidFuzz#33]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-89-72c32c429ab1> in <module>
----> 1 from rapidfuzz import process

C:\Program Files\Anaconda3\envs\proj\lib\site-packages\rapidfuzz\__init__.py in <module>
      2 rapid string matching library
      3 """
----> 4 from rapidfuzz import process, fuzz, levenshtein, utils

C:\Program Files\Anaconda3\envs\proj\lib\site-packages\rapidfuzz\process.py in <module>
      3 # Copyright © 2011 Adam Cohen
      4 
----> 5 from rapidfuzz import fuzz, utils
      6 from typing import Iterable, List, Tuple, Optional, Union, Callable, Generator
      7 import heapq

ImportError: DLL load failed: The specified module could not be found.

I'm currently getting the above ImportError when import the package in Python. Is it because the modules are supposed to be from fuzzywuzzy or another source?

**Comment by zhems** [comment]
Issue resolved by using conda-forge install instead.

**Comment by maxbachmann** [comment]
The issue is probably that the C++ redistributable is not installed, that is required to find c++ library.
This is now part of the installation description in the docs https://maxbachmann.github.io/rapidfuzz/installation/
