### ISSUE TITLE
update library dependencies

### ISSUE THREAD

**Issue by AurelienTurpin** [rapidfuzz/RapidFuzz#46]
Hello World =)

I'm using django 3.1.2 and rapidfuzz 0.12.3 is compatible only with Django <= 3.0.9, could you please update depencies for me to use it ?

Thanks ;)

**Comment by maxbachmann** [comment]
I am not quite sure which dependencies I should update. RapidFuzz does not has any dependencies

**Comment by AurelienTurpin** [comment]
I found the bug, I use poetry for dependencies managing and I have to update this library for rapidfuzz to be compatible with my django version.
Thanks for your fast response =)
