### ISSUE TITLE
Incorrect type annotation in `extractOne`

### ISSUE THREAD

**Issue by tamuhey** [rapidfuzz/RapidFuzz#48]
Here is the annotation of `extractOne`:

https://github.com/maxbachmann/rapidfuzz/blob/9b64ad2fee665b568ff3ff04aafdbadda2d8ed99/src/rapidfuzz/process.py#L138

But here returns `Tuple[str, float, str]`

https://github.com/maxbachmann/rapidfuzz/blob/9b64ad2fee665b568ff3ff04aafdbadda2d8ed99/src/rapidfuzz/process.py#L175

**Comment by maxbachmann** [comment]
Thanks for reporting. I updated the documentation and docstring.
