### ISSUE TITLE
Parametring weights of Levenstein distance

### ISSUE THREAD

**Issue by AurelienTurpin** [rapidfuzz/RapidFuzz#52]
Hi !

I would like to parameterize myself some weights of Levenstein distance. For instance, one of my project requires that I weight more deletion than replacement.
Could you make it possible ?

Thanks =)

**Comment by maxbachmann** [comment]
The algorithm used in the fuzz.* methods always uses a fixed weight of:
- deletion/insertion = 1
- replacement = 2

However when you directly use the `levenshtein.weighted_distance` function you can pass it weights:
> Calculates the minimum number of insertions, deletions, and substitutions
required to change one sequence into the other according to Levenshtein with custom
costs for insertion, deletion and substitution
Args:
    s1 (str):  first string to compare
    s2 (str):  second string to compare
    insert_cost (int): cost for insertions
    delete_cost (int): cost for deletions
    replace_cost (int): cost for substitutions
Returns:
    int: weighted levenshtein distance between s1 and s2


You can then use this to create your own scorer function, which you can pass to any of the processors aswell

**Comment by AurelienTurpin** [comment]
Thank you very much, it's exactly what I needed =)

Thanks for your fast answer ;)
