### ISSUE TITLE
my centos7 server must have gcc installed but still fails to install this library

### ISSUE THREAD

**Issue by marcusau** [rapidfuzz/RapidFuzz#58]
pip3 install rapidfuzz
Collecting rapidfuzz
  Using cached https://files.pythonhosted.org/packages/26/49/70355eeee8420ec4856a6e27146df8193ba14180cc416d33abdeb9e35b69/rapidfuzz-0.13.1.tar.gz
Installing collected packages: rapidfuzz
  Running setup.py install for rapidfuzz ... error
    Complete output from command /usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-g250_fyy/rapidfuzz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-357g06wr/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    running egg_info
    writing src/rapidfuzz.egg-info/PKG-INFO
    writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
    writing top-level names to src/rapidfuzz.egg-info/top_level.txt
    reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp'
    warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx'
    warning: no files found matching '*' under directory 'extern/boost'
    writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
    running build_ext
    building 'rapidfuzz.levenshtein' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/rapidfuzz-cpp/rapidfuzz -Isrc/rapidfuzz-cpp/extern -Iextern -I/usr/local/include/python3.7m -c src/py_levenshtein.cpp -o build/temp.linux-x86_64-3.7/src/py_levenshtein.o -O3 -std=c++14 -Wextra -Wall -DVERSION_INFO="0.13.1"
    gcc: error: unrecognized command line option ‘-std=c++14’
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-g250_fyy/rapidfuzz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-357g06wr/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-g250_fyy/rapidfuzz/

**Comment by maxbachmann** [comment]
I assume you're using a GCC version prior to gcc5.2, that does not has the flag ‘-std=c++14’.
Can you try to install from the repo using
```bash
git clone -b gcc_fix https://github.com/maxbachmann/rapidfuzz.git
cd rapidfuzz
pip install .
```

This uses '-std=c++1y' as fallback. I am currently not sure which features of C++14 I am using in here (most things should be C++11). So this might work.

**Comment by marcusau** [comment]
my gcc version is 

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


I have tried install from the repo  but the result is :

Installing collected packages: rapidfuzz
  Running setup.py install for rapidfuzz ... error
    Complete output from command /usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-iq1l8850/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d64g04is/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/__init__.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/fuzz.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/process.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    copying src/rapidfuzz/utils.py -> build/lib.linux-x86_64-3.7/rapidfuzz
    running egg_info
    creating src/rapidfuzz.egg-info
    writing src/rapidfuzz.egg-info/PKG-INFO
    writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
    writing top-level names to src/rapidfuzz.egg-info/top_level.txt
    writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
    reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.hpp' under directory 'src/rapidfuzz-cpp/rapidfuzz'
    warning: no files found matching '*.txx' under directory 'src/rapidfuzz-cpp/rapidfuzz'
    warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.hpp'
    warning: no previously-included files found matching 'src/rapidfuzz-cpp/rapidfuzz/process.txx'
    warning: no files found matching '*' under directory 'extern/boost'
    warning: no files found matching 'src/rapidfuzz-cpp/LICENSE'
    writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
    running build_ext
    creating tmp
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c /tmp/tmpt8uf5avm.cpp -o tmp/tmpt8uf5avm.o -std=c++14
    gcc: error: unrecognized command line option ‘-std=c++14’
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c /tmp/tmpfxd7pny8.cpp -o tmp/tmpfxd7pny8.o -std=c++1y
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-iq1l8850/setup.py", line 112, in <module>
        python_requires=">=2.7",
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-req-build-iq1l8850/setup.py", line 64, in build_extensions
        opts.append(cpp_flag(self.compiler))
      File "/tmp/pip-req-build-iq1l8850/setup.py", line 39, in cpp_flag
        raise RuntimeError('Unsupported compiler -- C++14 support is required!')
    RuntimeError: Unsupported compiler -- C++14 support is required!

    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-iq1l8850/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d64g04is/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-iq1l8850/
You are using pip version 10.0.1, however version 20.3b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by maxbachmann** [comment]
Thanks for reporting back. I will try this over the weekend.

**Comment by maxbachmann** [comment]
@marcusau I did test this on Centos7 now. There are a couple of issues.
1) apparently gcc 4.8.5 did not support all C++14 features requires by the library. https://github.com/maxbachmann/rapidfuzz-cpp is already C++11 compatible, so it is probably relatively straight forward to change the Python Version to C++11 aswell.
2) The reason for the current failure you see occurs when you do not have gcc with C++ support.
   You will have to install `gcc-c++` and `python3-devel`
3) your using a old version of pip that only support manylinux1 wheels. However I only ship wheels for manylinux2010, since manylinux1 is based on Centos5 which only supports C++11. (could be fixed when I add support for C++11).

For you there are a couple ways to get this to work on Centos7 right now
1) get a newer gcc version (>=5.2, that support C++14)
2) get a newer version of pip (>=19), that supports manylinux2010 wheels
3) you can get this to work with your current setup by manually downloading the wheels and renaming them:
```bash
wget https://files.pythonhosted.org/packages/eb/aa/ba3890bcd3a6e1ec7a625780283ca762144490f06b24f493df7528e41cc2/rapidfuzz-0.13.2-cp37-cp37m-manylinux2010_x86_64.whl

mv rapidfuzz-0.13.2-cp37-cp37m-manylinux2010_x86_64.whl rapidfuzz-0.13.2-cp37-cp37m-manylinux1_x86_64.whl
pip3 install rapidfuzz-0.13.2-cp37-cp37m-manylinux1_x86_64.whl
```

**Comment by marcusau** [comment]
Very detail explanation 
Thanks for your time 
I will try this tmr 
In Hong Kong it is mid night right now:)

Appreciate your contribution and effort

**Comment by maxbachmann** [comment]
@marcusau I did add C++11 support and manylinux1 wheels in v0.13.3.
Now it works to use
```bash
pip install rapidfuzz
```
on Centos7 aswell

**Comment by maxbachmann** [comment]
This should work now. Please reopen in case it does not.
