### ISSUE TITLE
Persistent "dead Jupyter kernel" issue with the latest version (v0.13.1) hosted on conda-forge

### ISSUE THREAD

**Issue by kxchia1** [rapidfuzz/RapidFuzz#60]
Hi there,

First of all, thanks so much for this useful library. Despite having installed the latest version, I keep seeing the "dead Jupyer kernel" issue when applying `process.extractOne` to a Pandas dataframe column containing more than 1000 rows, as documented [here](https://github.com/maxbachmann/rapidfuzz/issues/26). The issue went away after I downgraded to v0.7.6

**Comment by maxbachmann** [comment]
Hm probably a issue with the new implementation. I will look into it

**Comment by maxbachmann** [comment]
This should be fixed in v0.13.2.
@kxchia1 can you test whether this fixes the bug for you?

**Comment by kxchia1** [comment]
Hi @maxbachmann sure thing I will get this tested later. Thanks for your help

**Comment by kxchia1** [comment]
Hi @maxbachmann the issue is resolved now - thanks for your help once again!
