### ISSUE TITLE
process.extractOne, too many values to unpack

### ISSUE THREAD

**Issue by evamaxfield** [rapidfuzz/RapidFuzz#64]
This is a note for others who encounter this error.

Short: if you were using `extractOne` in `v0.12.*`, you may need to change your usage going forward to allow for unpacking of an additional value `i` (the index or key of the value chosen).

I was doing something like this:
```python
choice, score = process.extractOne(s, choices)
```

This worked under `v0.12.*` but was changed in `v0.13.*`.
To have similar behavior in `v0.13.*`:
```python
choice, score, i = process.extractOne(s, choices)
```
Where `i` is the index of the chosen value from the choices provided.

This has been noted in the README and [documentation](https://maxbachmann.github.io/rapidfuzz/usage/process/#extractone) so I am simply logging this issue for any others who may have run into it as well. So either version pin to `0.12.5` or upgrade and unpack the `i` value.

---

Note to @maxbachmann, 

First off, let me say that I greatly appreciate your work on this library, makes life a lot easier on my end :slightly_smiling_face: 
Do you plan to release a `v1` of this package or is this package currently "stable". If you consider this package "stable" I would recommend bumping the version to `v1.0.0` and following [semver](https://semver.org/) so that we don't hit these issues in the future.

**Comment by maxbachmann** [comment]
@JacksonMaxfield thanks for adding this as a note, since others might run into this as well. As of v0.13 I consider the interfaces as stable.
#61 and #55 still have to be addressed. Afterwards the version can be bumped to `v1.0.0` and follow semver versioning
