### ISSUE TITLE
extractOne crashes on Mac

### ISSUE THREAD

**Issue by Neronuser** [rapidfuzz/RapidFuzz#65]
Hi!

rapidfuzz-0.13.3 crashes Python process or Jupyter kernel when running simple example on Mac OS Catalina 10.15.7 on a 2014 MacBook Pro 2,8 GHz Dual-Core Intel Core i5.

Example:
```
Python 3.7.3 (default, May 13 2020, 14:01:50) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rapidfuzz import fuzz, process
>>> process.extract("hello", ["abc", "hello", "gbd", "hello"])
[('hello', 100.0, 1), ('hello', 100.0, 3), ('abc', 0.0, 0), ('gbd', 0.0, 2)]
>>> process.extractOne("hello", ["abc", "hello", "gbd", "hello"])
[1]    36550 illegal hardware instruction  python
```

Seems like a hardware support issue, older versions (before 0.13) work fine.

**Comment by maxbachmann** [comment]
Thanks for reporting. Version 0.13.4 fixes this issue in the CI. 
Can you try whether it works for you with the new release as well?

**Comment by Neronuser** [comment]
It works! 
Thanks a lot for fixing it so quickly.
