### ISSUE TITLE
import can't find rapidfuzz.cpp_impl

### ISSUE THREAD

**Issue by createcandle** [rapidfuzz/RapidFuzz#73]
I use Radpidfuzz in Voco, a privacy focussed voice control addon for the WebThings Gateway smart home controller.

I'm running into an issue loading rapidfuzz (`import can't find rapidfuzz.cpp_impl`), and I'm not sure what's causing it.

Is Rapidfuzz compatible with this method of installing it?

`pip3 install -r requirements.txt -t lib --no-binary :all: --prefix ""`

**Comment by maxbachmann** [comment]
I just tried a similar installation:
```
pip3 install rapidfuzz -t lib --no-binary :all: --prefix ""
```
which correctly installed the module into lib/rapidfuzz. 
```bash
>>> import rapidfuzz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rapidfuzz'
>>> import sys
>>> sys.path.append('lib')
>>> import rapidfuzz
```

I assume in your case either the shared object for `cpp_impl` is not created correctly (In my case thats `lib/rapidfuzz/cpp_impl.cpython-36dm-x86_64-linux-gnu.so`) or there is a problem with the search path.

**Comment by maxbachmann** [comment]
@createcandle could you get it to work?

**Comment by createcandle** [comment]
To be honest I just wanted to fix it quickly and was able to work around the dependency on Rapidfuzz.
