### ISSUE TITLE
Bug when using pandas series as fyzzu matching list

### ISSUE THREAD

**Issue by hugo-quantmetry** [rapidfuzz/RapidFuzz#81]
Hello,
I have a very weird and specific bug happening with rapidfuzz 1.1.1 (doesn't happen in 0.13.0)
Rapidfuzz crashes in that precise situation:

```
import rapidfuzz
import pandas as pd
matches = rapidfuzz.process.extract(
    "test",
    pd.Series(['test color brightness', 'test lemon', 'test lavender'], index=[67478, 67479, 67480]),
)
```

- If i convert the pandas Series to a list it works
- If I use default Series indexing it works

The bug seems to happen only in that very specific case.
Also if I use "test test" as input my notebook kernel directly dies.

Do you know where it comes from?
See below the traceback when I get to see it:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: <pandas._libs.hashtable.Int64HashTable object at 0x7f28586fe2f0>

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-3-4d95beb2db19> in <module>
      3 matches = rapidfuzz.process.extract(
      4     "test",
----> 5     pd.Series(['test color brightness', 'test lemon', 'test lavender'], index=[67478, 67479, 67480]),
      6 )
      7 matches

src/cpp_process.pyx in cpp_process.extract()

src/cpp_process.pyx in cpp_process.extract_dict()

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/series.py in __getitem__(self, key)
    904             return self._get_values(key)
    905 
--> 906         return self._get_with(key)
    907 
    908     def _get_with(self, key):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/series.py in _get_with(self, key)
    923         elif not is_list_like(key):
    924             # e.g. scalars that aren't recognized by lib.is_scalar, GH#32684
--> 925             return self.loc[key]
    926 
    927         if not isinstance(key, (list, np.ndarray, ExtensionArray, Series, Index)):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/indexing.py in __getitem__(self, key)
    877 
    878             maybe_callable = com.apply_if_callable(key, self.obj)
--> 879             return self._getitem_axis(maybe_callable, axis=axis)
    880 
    881     def _is_scalar_access(self, key: Tuple):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1108         # fall thru to straight lookup
   1109         self._validate_key(key, axis)
-> 1110         return self._get_label(key, axis=axis)
   1111 
   1112     def _get_slice_axis(self, slice_obj: slice, axis: int):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/indexing.py in _get_label(self, label, axis)
   1057     def _get_label(self, label, axis: int):
   1058         # GH#5667 this will fail if the label is not present in the axis.
-> 1059         return self.obj.xs(label, axis=axis)
   1060 
   1061     def _handle_lowerdim_multi_index_axis0(self, tup: Tuple):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/generic.py in xs(self, key, axis, level, drop_level)
   3491             loc, new_index = self.index.get_loc_level(key, drop_level=drop_level)
   3492         else:
-> 3493             loc = self.index.get_loc(key)
   3494 
   3495             if isinstance(loc, np.ndarray):

~/data-perrierh/src/asu-ds/venv-ds/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: <pandas._libs.hashtable.Int64HashTable object at 0x7f28586fe2f0>

**Comment by maxbachmann** [comment]
Thanks for reporting this. Apparently pandas created the index objects while iterating, so Python might already deallocate them when I do not increase their ref count. This should be fixed in v1.1.2.
