### ISSUE TITLE
`process.extract` returns unexpected results with `fuzz.ratio` as the scorer

### ISSUE THREAD

**Issue by ogdenkev** [rapidfuzz/RapidFuzz#92]
Thank you for the awesome work on RapidFuzz. I'm really loving the speed! I found that sometimes `process.extract` does not return the expected results. Here is an example.

```python
from rapidfuzz import fuzz, process
choices = [
    "NFL NFC South Atlanta Falcons",
    "NFL AFC East New York Jets",
    "NFL AFC East New York Jets Fan",
    "NFL NFC East New York Giants",
    "NFL NFC East Dallas Cowboys"
]
query = "Last year, who won first place at the NFL AFC East New York Jets Fan competition?"
process.extract(query, choices, scorer=fuzz.ratio, processor=None, limit=5)
```

This returns the following.

```
[('NFL AFC East New York Jets', 48.598130841121495, 1),
 ('NFL AFC East New York Jets Fan', 46.846846846846844, 2),
 ('NFL NFC East New York Giants', 42.20183486238532, 3),
 ('NFL NFC East Dallas Cowboys', 27.77777777777777, 4),
 ('NFL NFC South Atlanta Falcons', 25.454545454545453, 0)]
```

This is surprising. I would have expected `NFL AFC East New York Jets Fan` to have a higher score than `NFL AFC East New York Jets`. Moreover, the scores themselves do not match what `fuzz.ratio` returns when run on each choice individually, as in

```python
sorted(
    [(text, fuzz.ratio(query, text)) for text in choices],
    key=lambda tup: tup[1],
    reverse=True
)
```

which returns

```
[('NFL AFC East New York Jets Fan', 54.054054054054056),
 ('NFL AFC East New York Jets', 48.598130841121495),
 ('NFL NFC East New York Giants', 44.03669724770642),
 ('NFL NFC East Dallas Cowboys', 29.629629629629633),
 ('NFL NFC South Atlanta Falcons', 29.090909090909093)]
```

I thought this might be related to the query length and/or the length of the choices. For instance, with the query `Last year, who won the NFL AFC East New York Jets Fan contest` the results are as expected and the scores match those of `fuzz.ratio`. However, it looks like it may be related to [issue 90](https://github.com/maxbachmann/RapidFuzz/issues/90) in not finding the best substring. Yet, using `fuzz.partial_ratio` does not seem to have the discrepancies.

Thanks for any help on this issue!

I tested using rapidfuzz version 1.2.0.

**Comment by maxbachmann** [comment]
Thanks for reporting. I fixed this issue in release [v.1.3.0](https://github.com/maxbachmann/RapidFuzz/releases/tag/v1.3.0). I will keep this issue open as a reminder to add some more fuzz tests to catch similar issues in the future.

**Comment by maxbachmann** [comment]
This is now covered with fuzz tests as well.
